-- 002b_load_stg_regioes.sql
-- Carga automatica da planilha local para staging.stg_regioes
begin;
truncate table staging.stg_regioes;
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Araranguá', 'Sul', '52.898', '54.616', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Armazém', 'Sul', '6.543', '7.212', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Balneário Arroio do Silva', 'Sul', '11.564', '12.478', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Balneário Gaivota', 'Sul', '10.527', '12.233', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Balneário Rincão', 'Sul', '12.430', '13.177', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Braço do Norte', 'Sul', '24.805', '25.390', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Capivari de Baixo', 'Sul', '17.746', '18.515', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Cocal do Sul', 'Sul', '14.344', '14.899', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Criciúma', 'Sul', '152.206', '154.638', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ermo', 'Sul', '2.210', '2.672', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Forquilhinha', 'Sul', '20.798', '22154', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Garopaba', 'Sul', '21.287', '23132', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Grão Pará', 'Sul', '5.599', '5.207', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Gravatal', 'Sul', '9.002', '9470', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Içara', 'Sul', '42243', '43639', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Imaruí', 'Sul', '9551', '10111', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Imbituba', 'Sul', '39487', '41547', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Jacinto Machado', 'Sul', '9107', '9205', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Jaguaruna', 'Sul', '15206', '16158', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Laguna', 'Sul', '35918', '36462', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Lauro Müller', 'Sul', '12290', '12534', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Maracajá', 'Sul', '6316', '6423', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Meleiro', 'Sul', '6039', '5857', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Morro da Fumaça', 'Sul', '13471', '14012', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Morro Grande', 'Sul', '2787', '2687', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Nova Veneza', 'Sul', '12194', '12586', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Orleans', 'Sul', '19188', '19509', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Passo de Torres', 'Sul', '7281', '8808', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Pedras Grandes', 'Sul', '4153', '4207', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Pescaria Brava', 'Sul', '7677', '8365', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Praia Grande', 'Sul', '6354', '6549', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rio Fortuna', 'Sul', '4346', '4385', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Sangão', 'Sul', '8446', '8979', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Santa Rosa de Lima', 'Sul', '1981', '2033', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Santa Rosa do Sul', 'Sul', '7430', '7709', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São João do Sul', 'Sul', '6687', '7315', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Ludgero', 'Sul', '9205', '9716', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Martinho', 'Sul', '3238', '3192', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Siderópolis', 'Sul', '11105', '12175', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Sombrio', 'Sul', '22701', '21502', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Timbé do Sul', 'Sul', '4525', '4545', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Treviso', 'Sul', '3997', '3985', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Treze de Maio', 'Sul', '6591', '6497', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Tubarão', 'Sul', '81025', '82244', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Turvo', 'Sul', '9957', '10270', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Urussanga', 'Sul', '17472', '17722', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Águas Mornas', 'Grande Florianópolis', '6054', '6485', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Alfredo Wagner', 'Grande Florianópolis', '7661', '8052', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Angelina', 'Grande Florianópolis', '4995', '5081', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Anitápolis', 'Grande Florianópolis', '3147', '3314', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Antônio Carlos', 'Grande Florianópolis', '8345', '9111', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Biguaçu', 'Grande Florianópolis', '53041', '56158', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Canelinha', 'Grande Florianópolis', '9206', '10126', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Florianópolis', 'Grande Florianópolis', '399606', '410812', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Governador Celso Ramos', 'Grande Florianópolis', '14682', '16864', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Leoberto Leal', 'Grande Florianópolis', '3182', '3284', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Major Gercino', 'Grande Florianópolis', '3109', '3339', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Nova Trento', 'Grande Florianópolis', '10774', '11253', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Palhoça', 'Grande Florianópolis', '140096', '146889', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Paulo Lopes', 'Grande Florianópolis', '6622', '7.358', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rancho Queimado', 'Grande Florianópolis', '3146', '3803', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Santo Amaro da Imperatriz', 'Grande Florianópolis', '19055', '19705', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Bonifácio', 'Grande Florianópolis', '2777', '2915', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São João Batista', 'Grande Florianópolis', '22763', '23277', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São José', 'Grande Florianópolis', '186561', '191370', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Pedro de Alcântara', 'Grande Florianópolis', '4143', '4716', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Tijucas', 'Grande Florianópolis', '31771', '34348', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Araquari', 'Região Norte', '23917', '26525', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Balneário Barra do Sul', 'Região Norte', '10852', '11019', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Bela Vista do Toldo', 'Planalto Norte', '5118', '5273', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Campo Alegre', 'Planalto Norte', '9801', '10144', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Canoinhas', 'Planalto Norte', '42924', '43432', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Corupá', 'Região Norte', '11468', '11858', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Garuva', 'Região Norte', '11754', '12262', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Guaramirim', 'Região Norte', '32165', '33478', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Irineópolis', 'Planalto Norte', '8029', '8408', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Itaiópolis', 'Planalto Norte', '17012', '16504', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Itapoá', 'Região Norte', '17560', '20166', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Jaraguá do Sul', 'Região Norte', '122232', '126025', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Joinville', 'Região Norte', '428730', '434821', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Mafra', 'Planalto Norte', '41455', '42233', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Major Vieira', 'Planalto Norte', '5909', '6069', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Massaranduba', 'Região Norte', '13038', '13312', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Monte Castelo', 'Planalto Norte', '7164', '6966', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Papanduva', 'Planalto Norte', '14318', '14757', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Porto União', 'Planalto Norte', '25794', '26200', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rio Negrinho', 'Planalto Norte', '32189', '32729', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Santa Terezinha', 'Região Norte', '6573', '6712', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Bento do Sul', 'Planalto Norte', '63102', '64230', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Francisco do Sul', 'Região Norte', '39643', '42083', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Schroeder', 'Região Norte', '13827', '13705', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Timbó Grande', 'Planalto Norte', '5733', '6076', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Três Barras', 'Planalto Norte', '14947', '15372', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Abelardo Luz', 'Oeste', '12816', '12813', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Água Doce', 'Meio Oeste', '5459', '5613', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Águas de Chapecó', 'Oeste', '4761', '4757', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Águas Frias', 'Oeste', '2495', '2534', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Alto Bela Vista', 'Oeste', '1852', '1784', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Anchieta', 'Oeste', '4966', '5065', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Arabutã', 'Oeste', '3841', '3847', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Arroio Trinta', 'Meio Oeste', '3177', '3113', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Arvoredo', 'Oeste', '2450', '2617', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Bandeirante', 'Oeste', '2892', '2915', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Barra Bonita', 'Oeste', '1844', '1801', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Belmonte', 'Oeste', '2404', '2398', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Bom Jesus', 'Oeste', '2504', '2569', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Bom Jesus do Oeste', 'Oeste', '1889', '1882', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Caçador', 'Meio Oeste', '53740', '54065', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Caibi', 'Oeste', '4929', '5293', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Calmon', 'Planalto Norte', '3204', '3211', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Campo Erê', 'Oeste', '7239', '7524', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Capinzal', 'Meio Oeste', '17209', '17114', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Catanduvas', 'Meio Oeste', '8215', '8053', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Caxambu do Sul', 'Oeste', '4370', '4485', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Chapecó', 'Oeste', '159323', '161252', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Concórdia', 'Oeste', '59654', '60225', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Cordilheira Alta', 'Oeste', '4017', '4103', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Coronel Freitas', 'Oeste', '8163', '8147', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Coronel Martins', 'Oeste', '1972', '2081', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Cunha Porã', 'Oeste', '8548', '8757', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Cunhataí', 'Oeste', '1762', '1854', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Descanso', 'Oeste', '7026', '7188', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Dionísio Cerqueira', 'Oeste', '11669', '12156', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Entre Rios', 'Oeste', '2975', '3093', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Erval Velho', 'Meio Oeste', '3964', '3836', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Faxinal dos Guedes', 'Oeste', '8872', '8685', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Flor do Sertão', 'Oeste', '1731', '1731', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Formosa do Sul', 'Oeste', '2406', '2664', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Fraiburgo', 'Meio Oeste', '27947', '26426', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Galvão', 'Oeste', '2713', '2821', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Guaraciaba', 'Oeste', '9049', '8735', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Guarujá do Sul', 'Oeste', '4013', '4023', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Guatambu', 'Oeste', '5.649', '6.138', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Herval d''Oeste', 'Meio Oeste', '16.818', '17.014', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ibiam', 'Meio Oeste', '1826', '1980', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ibicaré', 'Meio Oeste', '2986', '3040', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Iomerê', 'Meio Oeste', '2771', '2864', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ipira', 'Oeste', '3842', '3889', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Iporã do Oeste', 'Oeste', '7285', '7521', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ipuaçu', 'Oeste', '5574', '5781', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ipumirim', 'Oeste', '6061', '6128', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Iraceminha', 'Oeste', '3674', '3718', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Irani', 'Oeste', '7522', '7745', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Irati', 'Oeste', '2047', '2087', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Itá', 'Oeste', '6011', '5857', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Itapiranga', 'Oeste', '12358', '12368', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Jaborá', 'Oeste', '3803', '3875', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Jardinópolis', 'Oeste', '1606', '1723', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Joaçaba', 'Meio Oeste', '22613', '22570', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Jupiá', 'Oeste', '2138', '2267', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Lacerdópolis', 'Meio Oeste', '2028', '1962', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Lajeado Grande', 'Oeste', '1472', '1599', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Lebon Régis', 'Meio Oeste', '8901', '8729', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Lindóia do Sul', 'Oeste', '3650', '3882', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Luzerna', 'Meio Oeste', '5017', '4839', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Macieira', 'Meio Oeste', '1774', '2419', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Maravilha', 'Oeste', '20302', '19942', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Marema', 'Oeste', '2004', '2257', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Matos Costa', 'Planalto Norte', '2464', '2447', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Modelo', 'Oeste', '3398', '3478', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Mondaí', 'Oeste', '7683', '7344', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Nova Erechim', 'Oeste', '3862', '4047', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Nova Itaberaba', 'Oeste', '3942', '3898', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Novo Horizonte', 'Oeste', '2469', '2608', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ouro', 'Meio Oeste', '5819', '5786', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ouro Verde', 'Oeste', '2014', '2069', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Paial', 'Oeste', '1940', '2013', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Palma Sola', 'Oeste', '5726', '5263', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Palmitos', 'Oeste', '12227', '12293', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Paraíso', 'Oeste', '3719', '3725', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Passos Maia', 'Oeste', '3328', '3473', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Peritiba', 'Oeste', '2744', '2841', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Pinhalzinho', 'Oeste', '15074', '15468', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Pinheiro Preto', 'Meio Oeste', '2802', '3060', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Piratuba', 'Meio Oeste', '5079', '5280', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Planalto Alegre', 'Oeste', '2761', '2937', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ponte Serrada', 'Oeste', '7965', '8204', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Presidente Castello Branco', 'Oeste', '1627', '1655', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Princesa', 'Oeste', '2562', '2560', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Quilombo', 'Oeste', '8187', '8184', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rio das Antas', 'Meio Oeste', '5308', '5316', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Riqueza', 'Oeste', '4088', '3977', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Romelândia', 'Oeste', '3934', '4172', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Saltinho', 'Oeste', '3287', '3297', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Salto Veloso', 'Meio Oeste', '3462', '3475', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Santa Helena', 'Oeste', '2264', '2244', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Santa Terezinha do Progresso', 'Oeste', '2454', '2497', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Santiago do Sul', 'Oeste', '1442', '1540', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Bernardino', 'Oeste', '2463', '2594', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Carlos', 'Oeste', '8259', '8199', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Domingos', 'Oeste', '7279', '7376', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São João do Oeste', 'Oeste', '5127', '5029', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São José do Cedro', 'Oeste', '11360', '10952', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Lourenço do Oeste', 'Oeste', '19151', '19222', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Miguel da Boa Vista', 'Oeste', '1716', '1752', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Miguel do Oeste', 'Oeste', '31895', '32001', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Saudades', 'Oeste', '7522', '7593', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Seara', 'Oeste', '14543', '13922', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Serra Alta', 'Oeste', '2815', '2794', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Sul Brasil', 'Oeste', '2426', '2391', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Tangará', 'Meio Oeste', '6601', '6736', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Tigrinhos', 'Oeste', '1999', '2055', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Treze Tílias', 'Meio Oeste', '6162', '6193', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Tunápolis', 'Oeste', '4035', '3974', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('União do Oeste', 'Oeste', '2470', '2471', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Vargeão', 'Oeste', '2933', '3024', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Vargem Bonita', 'Oeste', '4059', '3995', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Videira', 'Meio Oeste', '38678', '39255', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Xanxerê', 'Oeste', '36065', '34349', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Xavantina', 'Oeste', '3520', '3385', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Xaxim', 'Oeste', '22602', '23032', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Abdon Batista', 'Meio Oeste', '2506', '2656', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Anita Garibaldi', 'Serra', '7476', '6925', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Bocaina do Sul', 'Serra', '3128', '3149', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Bom Jardim da Serra', 'Serra', '3631', '4004', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Bom Retiro', 'Serra', '6513', '6591', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Brunópolis', 'Meio Oeste', '2772', '2894', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Campo Belo do Sul', 'Serra', '5983', '6075', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Campos Novos', 'Meio Oeste', '26706', '27111', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Capão Alto', 'Serra', '2928', '3158', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Celso Ramos', 'Meio Oeste', '2584', '2758', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Cerro Negro', 'Serra', '3215', '3221', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Correia Pinto', 'Serra', '11889', '12221', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Curitibanos', 'Meio Oeste', '31501', '31598', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Frei Rogério', 'Meio Oeste', '2275', '2228', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Lages', 'Serra', '125963', '126235', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Monte Carlo', 'Meio Oeste', '7162', '7062', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Otacílio Costa', 'Serra', '13366', '12720', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Painel', 'Serra', '2510', '2595', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Palmeira', 'Serra', '2841', '3214', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ponte Alta', 'Serra', '4152', '4071', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ponte Alta do Norte', 'Meio Oeste', '2619', '2748', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rio Rufino', 'Serra', '2309', '2444', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Santa Cecília', 'Planalto Norte', '13032', '12272', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Cristóvão do Sul', 'Meio Oeste', '3475', '3617', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São Joaquim', 'Serra', '19332', '19585', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São José do Cerrito', 'Serra', '7444', '7612', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Urubici', 'Serra', '8402', '7861', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Urupema', 'Serra', '2362', '2549', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Vargem', 'Meio Oeste', '2577', '2637', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Zortéa', 'Meio Oeste', '2997', '3131', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Agrolândia', 'Vale do Itajaí', '8007', '8143', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Agronômica', 'Vale do Itajaí', '4351', '4479', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Apiúna', 'Vale do Itajaí', '8202', '8475', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ascurra', 'Vale do Itajaí', '6354', '6689', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Atalanta', 'Vale do Itajaí', '2900', '2960', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Aurora', 'Vale do Itajaí', '5112', '5521', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Balneário Camboriú', 'Vale do Itajaí', '101641', '106783', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Balneário Piçarras', 'Vale do Itajaí', '18484', '21163', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Barra Velha', 'Vale do Itajaí', '26993', '27378', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Benedito Novo', 'Vale do Itajaí', '8245', '8389', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Blumenau', 'Vale do Itajaí', '261742', '265491', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Bombinhas', 'Vale do Itajaí', '16923', '18655', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Botuverá', 'Vale do Itajaí', '4316', '4698', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Braço do Trombudo', 'Vale do Itajaí', '3087', '3306', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Brusque', 'Vale do Itajaí', '94898', '98652', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Camboriú', 'Vale do Itajaí', '56981', '60580', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Chapadão do Lageado', 'Vale do Itajaí', '2564', '2690', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Dona Emma', 'Vale do Itajaí', '3223', '3480', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Doutor Pedrinho', 'Vale do Itajaí', '3009', '3076', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Gaspar', 'Vale do Itajaí', '49386', '51156', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Guabiruba', 'Vale do Itajaí', '16027', '16682', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ibirama', 'Vale do Itajaí', '15225', '15511', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ilhota', 'Vale do Itajaí', '11357', '12179', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Imbuia', 'Vale do Itajaí', '4908', '5160', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Indaial', 'Vale do Itajaí', '48509', '50363', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Itajaí', 'Vale do Itajaí', '163901', '174571', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Itapema', 'Vale do Itajaí', '50477', '55072', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Ituporanga', 'Vale do Itajaí', '19075', '19662', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('José Boiteux', 'Vale do Itajaí', '4295', '4429', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Laurentino', 'Vale do Itajaí', '5985', '5982', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Lontras', 'Vale do Itajaí', '8999', '9405', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Luiz Alves', 'Vale do Itajaí', '9930', '9907', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Mirim Doce', 'Vale do Itajaí', '2321', '2299', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Navegantes', 'Vale do Itajaí', '61069', '60845', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Penha', 'Vale do Itajaí', '22174', '24910', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Petrolândia', 'Vale do Itajaí', '5399', '5385', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Pomerode', 'Vale do Itajaí', '25935', '26798', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Porto Belo', 'Vale do Itajaí', '16821', '19124', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Pouso Redondo', 'Vale do Itajaí', '11816', '12292', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Presidente Getúlio', 'Vale do Itajaí', '13612', '14153', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Presidente Nereu', 'Vale do Itajaí', '2197', '2278', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rio do Campo', 'Vale do Itajaí', '5286', '5320', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rio do Oeste', 'Vale do Itajaí', '5984', '6154', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rio do Sul', 'Vale do Itajaí', '51421', '51474', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rio dos Cedros', 'Vale do Itajaí', '8800', '8744', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Rodeio', 'Vale do Itajaí', '9780', '9222', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Salete', 'Vale do Itajaí', '6062', '6301', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('São João do Itaperiú', 'Vale do Itajaí', '3745', '4195', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Taió', 'Vale do Itajaí', '14528', '14805', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Timbó', 'Vale do Itajaí', '34153', '35363', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Trombudo Central', 'Vale do Itajaí', '5234', '5478', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Vidal Ramos', 'Vale do Itajaí', '5349', '5329', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Vitor Meireles', 'Vale do Itajaí', '4472', '4457', 'inputs/regiao/cidade_regiao.csv');
insert into staging.stg_regioes (cidade, regiao, qtde_eleitores_2022, qtde_eleitores_2024, source_file) values ('Witmarsum', 'Vale do Itajaí', '3466', '3498', 'inputs/regiao/cidade_regiao.csv');
commit;
